---
title: "95_Make_Clean"
author:
- Andrew Davis, PhD, Unilever Human Biology
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::html_document:
    toc: TRUE
---

# Install/Load dependencies
```{r, echo=TRUE, message=FALSE, Loading_Dependencies}
# Install cran packages
list.of.packages <- c("here")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# Install Bioconductor packages
# bioc.packages <- c("Biobase")
# new.bioc.packages <- bioc.packages[!(bioc.packages %in% installed.packages()[,"Package"])]
# if(length(new.bioc.packages)) BiocManager::install(new.bioc.packages)

# Load dependencies:
library(here)
```

# Clean the Results directory before 99_Run_All.Rmd
```{r Clean, echo=TRUE}
dirs_to_clean <- c("Results")


if(!dir.exists(here(dirs_to_clean))){
  dir.create(here(dirs_to_clean))
}


for(i1 in 1:length(dirs_to_clean)){
  temp_file_list <- 
    dir(here(dirs_to_clean[i1]), recursive = TRUE)
  file.remove(here(dirs_to_clean[i1], temp_file_list))
}
```

