---
title: "99_Run_All"
author: "Andrew Davis, PhD, Unilever Human Biology"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::html_document:
    toc: TRUE
---


# Install/Load dependencies
```{r echo=TRUE, message=FALSE}
# Install cran packages
list.of.packages <- c("here","rmarkdown")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# Install Bioconductor packages
# bioc.packages <- c("Biobase")
# new.bioc.packages <- bioc.packages[!(bioc.packages %in% installed.packages()[,"Package"])]
# if(length(new.bioc.packages)) BiocManager::install(new.bioc.packages)

# Load dependencies:
library(here)
library(rmarkdown)
```

```{r Run_all, include=FALSE}
files_in_r_to_run <- 
  c("1.02_Hello-World.Rmd")

for(i1 in 1:length(files_in_r_to_run)){
  
  rmarkdown::render(here("Scripts", files_in_r_to_run[i1]),
                    output_format = 
                      html_document(html_preview = TRUE, toc = TRUE),
                    output_dir = here("Results"))
}

rmarkdown::render(here("README.Rmd"),
                  output_format =  html_document(html_preview = TRUE, toc = TRUE,keep_md=TRUE),
                  output_dir = here())

```
